title: Chandramouli Krishnamurthy
logo: /assets/img/profile_photo.png
description: I have 20+ years of experience working on test automation mainly in payroll domain. Currently doing my masters in Machine learning and artificial intelligence.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
